# =============================================
# Server Configuration
# =============================================
server.port=8081

# =============================================
# SQLite DataSource Configuration
# =============================================
spring.datasource.url=jdbc:sqlite:demo
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.username=
spring.datasource.password=

# =============================================
# JPA / Hibernate Configuration
# =============================================
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# =============================================
# SQL Initialisation — run schema.sql on startup
# =============================================
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql


# ==============================================
# Email (SMTP) Configuration - update with real values
# ==============================================
# ==============================================
# Email (SMTP) Configuration - Mailtrap for Development
# ==============================================
spring.mail.host=smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=67779005e0e28b
spring.mail.password=7aca10a677fea5
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.from=noreply@careapp.com

# ==============================================
# Stripe Secret Key (for dev/test)
# ==============================================
stripe.secret-key=sk_test_51THFSrHR7SQGzPyCzXLcETtKdgjCbjlbkHPQvdNSskjiZPeNXzL80b2FxCAMUKbZnAxHcH28z60xVYbMEOWdCgc8007c8IQ1fg


